#user config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: ${namespace}
data:
  users.conf: ftpadmin:Strongpass123:1001

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: ${namespace}
data:
  id_rsa.pub: ssh-rsa +++V0GTMwnk3hs= lecao@parrot
