apiVersion: v1
kind: Secret
metadata:
  name: sftp-host-keys
  namespace: ${namespace}
stringData:
  ssh_host_ed25519_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ....
    -----END OPENSSH PRIVATE KEY-----
  ssh_host_ed25519_key.pub: |
    ssh-ed25519 AAAAC3....
  ssh_host_rsa_key: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    .....
    -----END OPENSSH PRIVATE KEY-----
  ssh_host_rsa_key.pub: |
    ssh-rsa AAAAB3.......
type: Opaque