apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  kubernetes.io/change-cause: create deployment
  namespace: proxy
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources: 
        ports:
        - containerPort: 80
          name: nginx
        env:
          - name: ENV
            value: "1"

