apiVersion: v1
kind: Service
metadata:
  name: nginx  
  labels:                 
    app: nginx
  namespace: proxy
spec:
  ports:
  - port: 8098   
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
