apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio
  namespace: ${namespace}
spec:
  type: NodePort
  ports:
    - name: server-port
      port: 9000
      targetPort: 9000
      nodePort: 30009
      protocol: TCP

    - name: console-port
      port: 9001
      targetPort: 9001
      nodePort: 30010
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio