apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: ${namespace}
spec:
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: exterenal
      port: 9093
      targetPort: 9093
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_LISTENERS
          value: LISTENER_INTERNAL://kafka:9092,LISTENER_EXTERNAL://0.0.0.0:9093
        - name: KAFKA_ADVERTISED_LISTENERS
          value: LISTENER_INTERNAL://kafka:9092,LISTENER_EXTERNAL://192.168.3.80:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: LISTENER_INTERNAL
        image: wurstmeister/kafka:2.13-2.7.0
        imagePullPolicy: Always
        name: kafka
        resource:
        ports:
        - containerPort: 9092
        volumeMounts:
          - mountPath: /var/lib/kafka
            name: kafka-dev-volume
      volumes:
        - name: kafka-dev-volume
          hostPath:
            path: /var/lib/docker/volumes/kafka-dev #directory on host
            type: DirectoryOrCreate #optional