apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: ${namespace}
spec:
  # type: 
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: ${namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec: 
      containers:
        - image: zookeeper
          imagePullPolicy: Always
          name: zookeeper
          resource:
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /data
              name: zk-dev-volume
      volumes:
        - name: zk-dev-volume
          hostPath:
            path: /var/lib/docker/volumes/zk-dev #directory on host
            type: DirectoryOrCreate #optional